// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use javascriptcore_sys;
use std::ffi::CStr;

#[cfg(any(feature = "v2_24", feature = "dox"))]
lazy_static! {
    pub static ref OPTIONS_USE_DFG: &'static str = unsafe{CStr::from_ptr(javascriptcore_sys::JSC_OPTIONS_USE_DFG).to_str().unwrap()};
}
#[cfg(any(feature = "v2_24", feature = "dox"))]
lazy_static! {
    pub static ref OPTIONS_USE_FTL: &'static str = unsafe{CStr::from_ptr(javascriptcore_sys::JSC_OPTIONS_USE_FTL).to_str().unwrap()};
}
#[cfg(any(feature = "v2_24", feature = "dox"))]
lazy_static! {
    pub static ref OPTIONS_USE_JIT: &'static str = unsafe{CStr::from_ptr(javascriptcore_sys::JSC_OPTIONS_USE_JIT).to_str().unwrap()};
}
#[cfg(any(feature = "v2_24", feature = "dox"))]
lazy_static! {
    pub static ref OPTIONS_USE_LLINT: &'static str = unsafe{CStr::from_ptr(javascriptcore_sys::JSC_OPTIONS_USE_LLINT).to_str().unwrap()};
}
