// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod context;
pub use self::context::{Context, ContextClass, NONE_CONTEXT};
pub use self::context::ContextExt;

mod exception;
pub use self::exception::{Exception, ExceptionClass, NONE_EXCEPTION};
pub use self::exception::ExceptionExt;

mod value;
pub use self::value::{Value, ValueClass, NONE_VALUE};
pub use self::value::ValueExt;

mod virtual_machine;
pub use self::virtual_machine::{VirtualMachine, VirtualMachineClass, NONE_VIRTUAL_MACHINE};

mod weak_value;
pub use self::weak_value::{WeakValue, WeakValueClass, NONE_WEAK_VALUE};
pub use self::weak_value::WeakValueExt;

mod enums;
pub use self::enums::CheckSyntaxMode;
pub use self::enums::CheckSyntaxResult;
#[cfg(any(feature = "v2_24", feature = "dox"))]
pub use self::enums::OptionType;

mod flags;
pub use self::flags::ValuePropertyFlags;

pub mod functions;

mod constants;
#[cfg(any(feature = "v2_24", feature = "dox"))]
pub use self::constants::OPTIONS_USE_DFG;
#[cfg(any(feature = "v2_24", feature = "dox"))]
pub use self::constants::OPTIONS_USE_FTL;
#[cfg(any(feature = "v2_24", feature = "dox"))]
pub use self::constants::OPTIONS_USE_JIT;
#[cfg(any(feature = "v2_24", feature = "dox"))]
pub use self::constants::OPTIONS_USE_LLINT;

#[doc(hidden)]
pub mod traits {
    pub use super::ContextExt;
    pub use super::ExceptionExt;
    pub use super::ValueExt;
    pub use super::WeakValueExt;
}
