[crate_name_overrides]
"java_script_core" = "javascriptcore"

[options]
girs_dir = "../gir-files"
work_mode = "sys"
min_cfg_version="2.4"
library = "JavaScriptCore"
version = "4.0"
single_version_file = "."
target_path = "."

external_libraries = [
   "GLib",
   "GObject",
]

